<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Romain">

        <?php echo $this->headTitle('Mon Super CDI Blog (auto deployed)')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->basePath(); ?>/css/bootstrap.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <style>
            body {
                padding-top: 50px;
            }
            
/*            label, input, textarea {
                display: block;
            }*/
        </style>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Changer la navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Mon super Blog !!!</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home'); ?>">Liste des articles</a></li>
                        <li><a href="<?php echo $this->url('article_ajouter'); ?>">Ajouter article</a></li>
                        <?php if($this->zfcUserIdentity()) : ?>
                            <li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Se déconnecter</a></li>
                        <?php else : ?>
                            <li><a href="<?php echo $this->url('zfcuser/login'); ?>">Se connecter</a></li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <?php echo $this->content; ?>
        </div><!-- /.container -->


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    </body>
</html>
